# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GQMvCeZPyaZ_TUvaRVuC75TIB6MSSQb4
"""

#Dail;y Tracking System
#make 4 files for four categories: food, exercise and other activities
#write program to store the data into corresponding file and to retrive the data from the corresponding file
def gettime():
  import datetime 
  return datetime.datetime.now()

print("Daily Tracking System")
k=int(input("Enter 1 for adding the data and 2 for retriving the data "))
if k==1:
  category=int(input("Enter 1 for food, 2 for exercise, 3 for studies and 4 for other activities "))
  if category==1:
    with open("food.txt","a") as op:
      item=input("Enter the item ")
      op.write(str(gettime())+" "+item+"\n")
      print("New item is added")
  elif category==2:
    with open("exercise.txt","a") as op:
      item=input("Enter the item ")
      op.write(str(gettime())+" "+item+"\n")
      print("New item is added")
  elif category==3:
    with open("study.txt","a") as op:
      sub=input("Enter the subject ")
      topic=input("Enter the topic ")
      op.write(str(gettime())+f" {sub} : {topic} \n")
      print("New item is added")
  elif category==4:
    with open("other_act.txt","a") as op:
      item=input("Enter the item ")
      op.write(str(gettime())+" "+item+"\n")
      print("New item is added")
  else:
     print("Enter a valid number")


if k==2:
  category=int(input("Enter 1 for food, 2 for exercise, 3 for studies and 4 for other activities " ))
  if category==1:
     with open("food.txt") as op:
      for line in op:
         print(line)
  elif category==2:
    with open("exercise.txt") as op:
      for line in op:
         print(line)
  elif category==3:
    with open("study.txt") as op:
      for line in op:
        print(line)
  elif category==4:
     with open("other_act.txt") as op:
      for line in op:
        print(line)